#ifndef BOARDCONFIG_H
#define BOARDCONFIG_H

#define CONSOLEUARTPERIPHERIAL				SYSCTL_PERIPH_UART0
#define CONSOLEUARTPINPERIPHERIAL			SYSCTL_PERIPH_GPIOA
#define CONSOLEUARTPERIPHERIALBASE			UART0_BASE
#define CONSOLEUARTPINPERIPHERIALBASE		GPIO_PORTA_BASE
#define CONSOLEUARTRXPINTYPE				GPIO_PA0_U0RX
#define CONSOLEUARTTXPINTYPE				GPIO_PA1_U0TX
#define CONSOLEUARTRXPIN					GPIO_PIN_0
#define CONSOLEUARTTXPIN 					GPIO_PIN_1

#define LED_1_PINPERIPHERIAL				SYSCTL_PERIPH_GPIOF
#define LED_2_PINPERIPHERIAL				SYSCTL_PERIPH_GPIOF
#define LED_3_PINPERIPHERIAL				SYSCTL_PERIPH_GPIOF
#define LED_ALL_PINPERIPHERIAL				SYSCTL_PERIPH_GPIOF
#define LED_1_PORTBASE						GPIO_PORTF_BASE
#define LED_2_PORTBASE						GPIO_PORTF_BASE
#define LED_3_PORTBASE						GPIO_PORTF_BASE
#define LED_ALL_PORTBASE					GPIO_PORTF_BASE
#define LED_RED_PORTBASE					LED_1_PORTBASE
#define LED_BLUE_PORTBASE					LED_2_PORTBASE
#define LED_GREEN_PORTBASE					LED_3_PORTBASE
#define LED_1_PIN 							GPIO_PIN_1
#define LED_2_PIN 							GPIO_PIN_2
#define LED_3_PIN 							GPIO_PIN_3
#define LED_RED								LED_1_PIN
#define LED_BLUE 							LED_2_PIN
#define LED_GREEN 							LED_3_PIN


#endif